import { getAuth, onAuthStateChanged } from "firebase/auth";
import Head from "next/head";

import { Contact, Landing, Services } from "../screens";
import Layout from "../screens/Layout";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { loginUser, logOutUser, selectUser } from "../app/slices/userSlice";

export default function Home() {
  const navigate = useRouter();
  const auth = getAuth();
  const dispatch = useDispatch();
  const user = useSelector(selectUser);

  return (
    <div>
      <Head>
        <title>Pizza - Best pizza you can get</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Landing />
          <section id="service">
            <Services />
          </section>
          <section id="contact">
            <Contact />
          </section>
        </Layout>
      </main>
    </div>
  );
}
