import Head from "next/head";

import { Contact, Landing, Services } from "../screens";
import Layout from "../screens/Layout";

import { useEffect, useState } from "react";
import { Loading } from "../components";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  if (loading) {
    return <Loading />;
  }

  return (
    <div>
      <Head>
        <title>Pizza - Best pizza you can get</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Landing />
          <section id="service">
            <Services />
          </section>
          <section id="contact">
            <Contact />
          </section>
        </Layout>
      </main>
    </div>
  );
}
