import Head from "next/head";

import Layout from "../screens/Layout";
import Profile from "../screens/Profile";

export default function profile() {
  return (
    <div>
      <Head>
        <title>Login - Pizza </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <div id="profile">
            <Profile />
          </div>
        </Layout>
      </main>
    </div>
  );
}
